name: taboosun_lints
description: TabooSun Lints for Dart projects.
version: 1.1.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.1
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
