name: taboosun_lints
description: TabooSun Lints for Dart projects.
version: 1.1.3

environment:
  sdk: '>=2.17.0 <3.0.0'
# homepage: https://www.example.com

dependencies:
  lints: ^2.0.0
  flutter_lints: ^2.0.1

# Code is not allowed in this package. Do not add any dependencies or dev_dependencies.